import { notFound } from "next/navigation"
import { prisma } from "@/lib/db"
import { AuditResults } from "@/components/AuditResults"
import type { AuditResult } from "@/lib/checks/types"
import Link from "next/link"

interface Props {
  params: Promise<{ id: string }>
}

export async function generateMetadata({ params }: Props) {
  const { id } = await params
  return {
    title: `Security Report — ShipSafe`,
    description: `Web security audit report generated by ShipSafe.`,
  }
}

export default async function ReportPage({ params }: Props) {
  const { id } = await params

  let result: AuditResult | null = null

  try {
    if (!prisma) notFound()
    const report = await prisma.auditReport.findUnique({ where: { id } })
    if (!report) notFound()
    result = report.result as unknown as AuditResult
  } catch {
    notFound()
  }

  if (!result) notFound()

  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      {/* Header */}
      <header
        style={{
          borderBottom: "1px solid var(--border)",
          position: "sticky",
          top: 0,
          background: "rgba(13,17,23,0.92)",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
          zIndex: 50,
        }}
      >
        <div
          style={{
            maxWidth: 860,
            margin: "0 auto",
            padding: "0 24px",
            height: 60,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <Link
            href="/"
            style={{
              fontWeight: 700,
              fontSize: 17,
              color: "var(--text)",
              textDecoration: "none",
              letterSpacing: "-0.02em",
              fontFamily: "var(--font-barlow, sans-serif)",
            }}
          >
            ShipSafe
          </Link>
          <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
            <span
              style={{
                fontSize: 13,
                color: "var(--text-muted)",
                fontFamily: "var(--font-barlow, sans-serif)",
              }}
            >
              Security report
            </span>
            <Link
              href="/"
              style={{
                fontSize: 13,
                color: "var(--text-muted)",
                textDecoration: "none",
                border: "1px solid var(--border)",
                padding: "5px 14px",
                borderRadius: 8,
                fontFamily: "var(--font-barlow, sans-serif)",
                transition: "border-color 0.15s",
              }}
            >
              ← New audit
            </Link>
          </div>
        </div>
      </header>

      <main style={{ maxWidth: 860, margin: "0 auto", padding: "48px 24px 80px" }}>
        {/* Page heading */}
        <div style={{ marginBottom: 32 }}>
          <h1
            style={{
              fontFamily: "var(--font-barlow, sans-serif)",
              fontSize: 22,
              fontWeight: 600,
              margin: "0 0 6px",
              color: "var(--text)",
              letterSpacing: "-0.01em",
            }}
          >
            Security audit report
          </h1>
          <p
            style={{
              fontSize: 15,
              color: "var(--text-muted)",
              margin: 0,
              lineHeight: 1.6,
              fontFamily: "var(--font-barlow, sans-serif)",
            }}
          >
            {result.url} — scanned on{" "}
            {new Date(result.scannedAt).toLocaleDateString("en-US", {
              weekday: "long",
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>
        </div>

        <AuditResults result={result} reportId={id} />

        {/* Footer */}
        <div
          style={{
            marginTop: 48,
            paddingTop: 24,
            borderTop: "1px solid var(--border)",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 12,
          }}
        >
          <Link
            href="/"
            style={{
              fontSize: 14,
              color: "var(--text-muted)",
              textDecoration: "none",
              fontFamily: "var(--font-barlow, sans-serif)",
            }}
          >
            ← Run another audit
          </Link>
          <span
            style={{
              fontSize: 13,
              color: "var(--text-dim)",
              fontFamily: "var(--font-barlow, sans-serif)",
            }}
          >
            Powered by ShipSafe · 19 parallel checks
          </span>
        </div>
      </main>
    </div>
  )
}
